version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - cherimoya-{{ checksum "pom.xml" }}
            - cherimoya
      - run:
          name: Install Cherimoya annotation library
          working_directory: ~/repo/cherimoya
          command: mvn install --batch-mode
      - run: mvn dependency:go-offline
      - run:
          name: Build and unit test
          command: |
            mvn install --batch-mode
      - save_cache:
          paths:
            - ~/.m2
          key: cherimoya-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
