version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: SonarCloud

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - cherimoya-{{ checksum "pom.xml" }}
            - cherimoya
      - run:
          name: Install Cherimoya annotation library
          working_directory: ~/repo/cherimoya
          command: mvn install -B
      - run: mvn dependency:go-offline -B
      - run:
          name: Quality quantification
          command: |
            mvn -B -Psonarcloud install sonar:sonar
      - save_cache:
          paths:
            - ~/.m2
          key: cherimoya-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
