version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: SonarCloud

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - polypara-{{ checksum "pom.xml" }}-{{ checksum "polypara/pom.xml" }}-{{ checksum "polypara-maven-plugin/pom.xml" }}
            - polypara
      - run:
          name: Install Cherimoya annotation library
          working_directory: ~/repo/polypara
          command: mvn install -B
      - run: mvn dependency:go-offline -B
      - run:
          name: Quality quantification
          command: |
            mvn -B -Psonarcloud install sonar:sonar
      - save_cache:
          paths:
            - ~/.m2
          key: polypara-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
